package com.gome.core.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.gome.work.core.model.dao.MyAppInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MY_APP_INFO".
*/
public class MyAppInfoDao extends AbstractDao<MyAppInfo, Long> {

    public static final String TABLENAME = "MY_APP_INFO";

    /**
     * Properties of entity MyAppInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AppId = new Property(1, String.class, "appId", false, "APP_ID");
        public final static Property DataUseId = new Property(2, String.class, "dataUseId", false, "DATA_USE_ID");
    }


    public MyAppInfoDao(DaoConfig config) {
        super(config);
    }
    
    public MyAppInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MY_APP_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"APP_ID\" TEXT," + // 1: appId
                "\"DATA_USE_ID\" TEXT);"); // 2: dataUseId
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_MY_APP_INFO_APP_ID_DATA_USE_ID ON \"MY_APP_INFO\"" +
                " (\"APP_ID\" ASC,\"DATA_USE_ID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MY_APP_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MyAppInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String appId = entity.getAppId();
        if (appId != null) {
            stmt.bindString(2, appId);
        }
 
        String dataUseId = entity.getDataUseId();
        if (dataUseId != null) {
            stmt.bindString(3, dataUseId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MyAppInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String appId = entity.getAppId();
        if (appId != null) {
            stmt.bindString(2, appId);
        }
 
        String dataUseId = entity.getDataUseId();
        if (dataUseId != null) {
            stmt.bindString(3, dataUseId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MyAppInfo readEntity(Cursor cursor, int offset) {
        MyAppInfo entity = new MyAppInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // appId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // dataUseId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MyAppInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAppId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDataUseId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MyAppInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MyAppInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MyAppInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
