package com.gome.core.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.gome.work.core.model.im.PushDataExtraInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PUSH_DATA_EXTRA_INFO".
*/
public class PushDataExtraInfoDao extends AbstractDao<PushDataExtraInfo, Long> {

    public static final String TABLENAME = "PUSH_DATA_EXTRA_INFO";

    /**
     * Properties of entity PushDataExtraInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Activity = new Property(1, String.class, "activity", false, "ACTIVITY");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property Extra = new Property(3, String.class, "extra", false, "EXTRA");
        public final static Property MsgId = new Property(4, String.class, "msgId", false, "MSG_ID");
        public final static Property Title = new Property(5, String.class, "title", false, "TITLE");
        public final static Property Url = new Property(6, String.class, "url", false, "URL");
        public final static Property IsRead = new Property(7, boolean.class, "isRead", false, "IS_READ");
        public final static Property AppId = new Property(8, String.class, "appId", false, "APP_ID");
    }


    public PushDataExtraInfoDao(DaoConfig config) {
        super(config);
    }
    
    public PushDataExtraInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PUSH_DATA_EXTRA_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ACTIVITY\" TEXT," + // 1: activity
                "\"CONTENT\" TEXT," + // 2: content
                "\"EXTRA\" TEXT," + // 3: extra
                "\"MSG_ID\" TEXT," + // 4: msgId
                "\"TITLE\" TEXT," + // 5: title
                "\"URL\" TEXT," + // 6: url
                "\"IS_READ\" INTEGER NOT NULL ," + // 7: isRead
                "\"APP_ID\" TEXT);"); // 8: appId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PUSH_DATA_EXTRA_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PushDataExtraInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String activity = entity.getActivity();
        if (activity != null) {
            stmt.bindString(2, activity);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
 
        String extra = entity.getExtra();
        if (extra != null) {
            stmt.bindString(4, extra);
        }
 
        String msgId = entity.getMsgId();
        if (msgId != null) {
            stmt.bindString(5, msgId);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(7, url);
        }
        stmt.bindLong(8, entity.getIsRead() ? 1L: 0L);
 
        String appId = entity.getAppId();
        if (appId != null) {
            stmt.bindString(9, appId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PushDataExtraInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String activity = entity.getActivity();
        if (activity != null) {
            stmt.bindString(2, activity);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
 
        String extra = entity.getExtra();
        if (extra != null) {
            stmt.bindString(4, extra);
        }
 
        String msgId = entity.getMsgId();
        if (msgId != null) {
            stmt.bindString(5, msgId);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(7, url);
        }
        stmt.bindLong(8, entity.getIsRead() ? 1L: 0L);
 
        String appId = entity.getAppId();
        if (appId != null) {
            stmt.bindString(9, appId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PushDataExtraInfo readEntity(Cursor cursor, int offset) {
        PushDataExtraInfo entity = new PushDataExtraInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // activity
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // content
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // extra
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // msgId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // title
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // url
            cursor.getShort(offset + 7) != 0, // isRead
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // appId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PushDataExtraInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setActivity(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setExtra(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMsgId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTitle(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIsRead(cursor.getShort(offset + 7) != 0);
        entity.setAppId(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PushDataExtraInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PushDataExtraInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PushDataExtraInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
