/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bochuan_pinke_jni_JNIBridge */

#ifndef _Included_com_bochuan_pinke_jni_JNIBridge
#define _Included_com_bochuan_pinke_jni_JNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bochuan_pinke_jni_JNIBridge
 * Method:    testJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bochuan_pinke_jni_JNIBridge_testJni
  (JNIEnv *env, jclass);

#ifdef __cplusplus
}
#endif
#endif
