/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bochuan_pinke_jni_JNIBridge */

#ifndef _Included_com_bochuan_pinke_jni_JNIBridge
#define _Included_com_bochuan_pinke_jni_JNIBridge
#ifdef __cplusplus

#include "com_bochuan_pinke_jni_JNIBridge.h"

#include <string>
#include <android/log.h>

#define LOG_TGA "native"
extern "C" {
#endif
/*
 * Class:     com_bochuan_pinke_jni_JNIBridge
 * Method:    testJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bochuan_pinke_jni_JNIBridge_testJni
        (JNIEnv *env, jclass) {
    std::string hello = "(*^__^*) 嘻嘻……~Hello from C++ 隔壁老李头";
    __android_log_print(ANDROID_LOG_DEBUG, LOG_TGA, "hello native log");
    return env->NewStringUTF(hello.c_str());
}

#ifdef __cplusplus
}
#endif
#endif
